### ISSUE TITLE
Regarding the E3FP rendering

### ISSUE THREAD

**Issue by VirtualChemist** [keiserlab/e3fp#48] opened 2020-11-18 23:44 UTC
Hi Dr Seth,

Could it be possible to apply the following rendering strategies to look into the kind of substructure captured by E3FP?

Here is one of the example for rendering the fingerprint bit (ECFP) for a structure.

http://rdkit.blogspot.com/2018/10/using-new-fingerprint-bit-rendering-code.html

if this rendering feature can be implemented in E3FP code.

Waiting for your kind support.

Thanks,
Surendra

**Comment by sethaxen** [comment] 2020-11-23 09:02
There are a few ways to answer this. ECFP is a graph fingerprint, so each "substructure" in ECFP will be a contiguous subgraph of the molecule. Hence, 2D visualizations like the ones you link to work great.
In E3FP, each identifier maps to a shell, which is a collection of all atoms within the current iteration's radius of an atom at the center of the shell. The identifier is not generated just from these atoms and their configurations but also from the identifiers of the shells around each of these atoms from the previous iteration, which could include atoms not yet within the shell. This collection of all atoms that have in any way determined the identifier for a specific atom in a specific iteration is called a substructure. Note that neither a shell nor a substructure guarantees connectedness, so a graph visualization may not be appropriate.

We used a 3D analog of the rendering you linked to in the [E3FP paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6075869/) (see e.g. Figure 1). If that interests you, then take a look at the scripts in the E3FP paper's repo: https://github.com/keiserlab/e3fp-paper/tree/master/project/analysis/visualization.

Alternatively, you could generate a fingerprint, retrieve the atoms in the shell or substructure, and then perhaps use some of RDKit's functionality to render contiguous and non-contiguous parts, but I won't be able to be much help there.

**Comment by VirtualChemist** [comment] 2020-11-23 09:44
Thanks for the explanation. I will test the visualization code and will see if it can help me to get an overview of feature interpretation.

Thanks,

**Comment by VirtualChemist** [comment] 2020-11-24 01:39
Hi Dr Seth,

Today, I tried to run the visualization script and I encountered the following error.
Before running the script. I installed PyGraphviz, NetworkX, and PyMOL under the e3fp_dev environment.


(e3fp_dev) [surendra@gpu visualization]$ pymol -r make_shell_figures.py -- CHEMBL2110918.sdf.bz2 
 PyMOL(TM) 2.4.1 - Incentive Product
 Copyright (C) Schrodinger, LLC
 
 This Executable Build integrates and extends Open-Source PyMOL.
 Detected OpenGL version 2.1. Shaders available.
 Geometry shaders not available
 SMAA not available
 Detected GLSL version 1.30.
 OpenGL graphics engine:
  GL_VENDOR:   VMware, Inc.
  GL_RENDERER: llvmpipe (LLVM 5.0, 256 bits)
  GL_VERSION:  2.1 Mesa 17.2.3
 License Expiry date: 01-jun-2021
 Detected 28 CPU cores.  Enabled multithreaded rendering.
PyMOL>run /home/surendra/Downloads/wSterimol/wsterimol/visualize.py
 Setting: ray_shadow set to on.
 Setting: light_count set to 2.
 Setting: light set to [ -0.40000, -0.40000, -1.00000 ].
 Setting: ambient set to 0.14000.
 Setting: direct set to 0.65000.
 Setting: reflect set to 0.25000.
 Setting: shininess set to 40.00000.
 Setting: power set to 1.00000.
 Setting: specular_intensity set to 0.50000.
 Setting: spec_direct set to 0.00000.
 Setting: spec_count set to -1.
 Setting: ray_shadow_decay_factor set to 0.00000.
PyMOL>run make_shell_figures.py,main
2020-11-24 10:32:34,194|DEBUG|Logging to stdout
2020-11-24 10:32:34,207|DEBUG|Read 1 conformers from CHEMBL2110918.sdf.bz2.
2020-11-24 10:32:34,255|DEBUG|Shell with identifier 661922864 at level 2 is not unique. Removing.
2020-11-24 10:32:34,256|DEBUG|Shell with identifier 1057074403 at level 2 is not unique. Removing.
2020-11-24 10:32:34,256|DEBUG|Shell with identifier 1266914156 at level 2 is not unique. Removing.
2020-11-24 10:32:34,256|DEBUG|Shell with identifier 1266914156 at level 2 is not unique. Removing.
2020-11-24 10:32:34,256|DEBUG|Shell with identifier 1936833248 at level 2 is not unique. Removing.
2020-11-24 10:32:34,275|DEBUG|Shell with identifier -2120100613 at level 3 is not unique. Removing.
2020-11-24 10:32:34,275|DEBUG|Shell with identifier -1459558800 at level 3 is not unique. Removing.
2020-11-24 10:32:34,276|DEBUG|Shell with identifier -889949098 at level 3 is not unique. Removing.
2020-11-24 10:32:34,276|DEBUG|Shell with identifier -260691027 at level 3 is not unique. Removing.
2020-11-24 10:32:34,276|DEBUG|Shell with identifier -115025741 at level 3 is not unique. Removing.
2020-11-24 10:32:34,276|DEBUG|Shell with identifier 35460490 at level 3 is not unique. Removing.
2020-11-24 10:32:34,276|DEBUG|Shell with identifier 300886491 at level 3 is not unique. Removing.
2020-11-24 10:32:34,277|DEBUG|Shell with identifier 383466322 at level 3 is not unique. Removing.
2020-11-24 10:32:34,277|DEBUG|Shell with identifier 525661536 at level 3 is not unique. Removing.
2020-11-24 10:32:34,277|DEBUG|Shell with identifier 586904987 at level 3 is not unique. Removing.
2020-11-24 10:32:34,277|DEBUG|Shell with identifier 671792618 at level 3 is not unique. Removing.
2020-11-24 10:32:34,278|DEBUG|Shell with identifier 1782835959 at level 3 is not unique. Removing.
2020-11-24 10:32:34,278|DEBUG|No new shells added. Convergence reached.
added edge between 3654310210 and 2146727905
added edge between 236364480 and 2146727905
added edge between 1355662222 and 2146727905
added edge between 3079013085 and 2146727905
added edge between 3654310210 and 2146727905
added edge between 236364480 and 2146727905
added edge between 236364480 and 2146727905
added edge between 526356276 and 563733172
added edge between 526356276 and 563733172
added edge between 526356276 and 563733172
added edge between 236364480 and 4222155853
added edge between 3654310210 and 4222155853
added edge between 3654310210 and 4222155853
added edge between 236364480 and 4222155853
added edge between 236364480 and 4222155853
added edge between 3079013085 and 4222155853
added edge between 2738552880 and 3079013085
added edge between 2453405156 and 3079013085
added edge between 3560653707 and 3079013085
added edge between 2453405156 and 3079013085
added edge between 2523886517 and 3471456286
added edge between 3560653707 and 3471456286
added edge between 486993694 and 714291194
added edge between 563733172 and 714291194
added edge between 1355662222 and 714291194
added edge between 3079013085 and 714291194
added edge between 3654310210 and 714291194
added edge between 486993694 and 714291194
added edge between 1377583001 and 714291194
added edge between 2453405156 and 3654310210
added edge between 2738552880 and 3654310210
added edge between 2453405156 and 3654310210
added edge between 3560653707 and 1355662222
added edge between 2738552880 and 1355662222
added edge between 526356276 and 1355662222
added edge between 3560653707 and 1355662222
added edge between 3471456286 and 3588767207
added edge between 1377583001 and 3588767207
added edge between 486993694 and 3588767207
added edge between 1355662222 and 3588767207
added edge between 3079013085 and 3588767207
added edge between 1355662222 and 2219502143
added edge between 563733172 and 2219502143
added edge between 3654310210 and 2219502143
added edge between 3079013085 and 2219502143
added edge between 486993694 and 2219502143
added edge between 1377583001 and 2219502143
added edge between 3654310210 and 2219502143
added edge between 486993694 and 2219502143
added edge between 3471456286 and 2219502143
added edge between 2453405156 and 236364480
added edge between 2453405156 and 236364480
added edge between 2453405156 and 236364480
added edge between 3079013085 and 3982335018
added edge between 3471456286 and 3982335018
added edge between 3654310210 and 3982335018
added edge between 236364480 and 3982335018
added edge between 1377583001 and 3982335018
added edge between 3654310210 and 3982335018
added edge between 236364480 and 3982335018
added edge between 1355662222 and 3982335018
added edge between 486993694 and 3982335018
added edge between 236364480 and 3982335018
added edge between 2453405156 and 3654310210
added edge between 2738552880 and 3654310210
added edge between 2453405156 and 3654310210
added edge between 3560653707 and 1377583001
added edge between 3560653707 and 1377583001
added edge between 526356276 and 1377583001
added edge between 2523886517 and 1377583001
added edge between 526356276 and 486993694
added edge between 526356276 and 486993694
added edge between 3560653707 and 486993694
added edge between 2453405156 and 236364480
added edge between 2453405156 and 236364480
added edge between 2453405156 and 236364480
added edge between 526356276 and 486993694
added edge between 3560653707 and 486993694
added edge between 526356276 and 486993694
added edge between 2453405156 and 236364480
added edge between 2453405156 and 236364480
added edge between 2453405156 and 236364480
added edge between 486993694 and 285017645
added edge between 3471456286 and 285017645
added edge between 563733172 and 285017645
added edge between 1377583001 and 285017645
added edge between 1355662222 and 285017645
added edge between 486993694 and 285017645
Traceback (most recent call last):
  File "/home/surendra/anaconda3/envs/e3fp_dev/lib/python2.7/site-packages/pymol/parsing.py", line 487, in run
    run_(path, ns_main, ns_main)
  File "/home/surendra/anaconda3/envs/e3fp_dev/lib/python2.7/site-packages/pymol/parsing.py", line 532, in run_file
    execfile(file,global_ns,local_ns)
  File "/home/surendra/anaconda3/envs/e3fp_dev/lib/python2.7/site-packages/pymol/parsing.py", line 527, in execfile
    exec(co, global_ns, local_ns)
  File "make_shell_figures.py", line 600, in <module>
    only_unique=True)
  File "make_shell_figures.py", line 163, in create_shell_graph
    nx.set_node_attributes(G, 'shell', identifier_to_shell)
  File "/home/surendra/anaconda3/envs/e3fp_dev/lib/python2.7/site-packages/networkx/classes/function.py", line 654, in set_node_attributes
    G.nodes[n][name] = values
TypeError: unhashable type: 'dict'


Can you please help us the type of error, it is listing. 

Thanks

**Comment by sethaxen** [comment] 2020-11-26 08:00
Hi, I should have some time to look into this next week. The `e3fp_paper` repo is not production code, and I would not be surprised if a change in Python or one of its dependencies introduced a bug. I see you are running Python 2. Have you tried it on Python 3?

**Comment by VirtualChemist** [comment] 2020-11-26 08:31
Hi,

Here is the testing on python3.

I encountered the same error.

(e3fp) [surendra@gpu visualization]$ pymol -r make_shell_figures.py -- CHEMBL2110918.sdf.bz2 
 PyMOL(TM) 2.3.5 - Incentive Product
 Copyright (C) Schrodinger, LLC
 
 This Executable Build integrates and extends Open-Source PyMOL.
 Detected OpenGL version 2.1. Shaders available.
 Geometry shaders not available
 SMAA not available
 Detected GLSL version 1.30.
 OpenGL graphics engine:
  GL_VENDOR:   VMware, Inc.
  GL_RENDERER: llvmpipe (LLVM 5.0, 256 bits)
  GL_VERSION:  2.1 Mesa 17.2.3
 License Expiry date: 01-jun-2021
 Detected 28 CPU cores.  Enabled multithreaded rendering.
PyMOL>run /home/surendra/Downloads/wSterimol/wsterimol/visualize.py
 Setting: ray_shadow set to on.
 Setting: light_count set to 2.
 Setting: light set to [ -0.40000, -0.40000, -1.00000 ].
 Setting: ambient set to 0.14000.
 Setting: direct set to 0.65000.
 Setting: reflect set to 0.25000.
 Setting: shininess set to 40.00000.
 Setting: power set to 1.00000.
 Setting: specular_intensity set to 0.50000.
 Setting: spec_direct set to 0.00000.
 Setting: spec_count set to -1.
 Setting: ray_shadow_decay_factor set to 0.00000.
PyMOL>run /home/surendra/Downloads/wSterimol/wsterimol/setup.py
PyMOL>run /home/surendra/Downloads/wSterimol/wsterimol/generate.py
PyMOL>run /home/surendra/Downloads/wSterimol/wsterimol/filter_gen.py
PyMOL>run /home/surendra/Downloads/wSterimol/wsterimol/prepare_file.py
PyMOL>run /home/surendra/Downloads/wSterimol/wsterimol/optimisation.py
PyMOL>run /home/surendra/Downloads/wSterimol/wsterimol/filter_opt.py
PyMOL>run /home/surendra/Downloads/wSterimol/wsterimol/sterimoltools.py
PyMOL>run /home/surendra/Downloads/wSterimol/wsterimol/sterimol.py
PyMOL>run /home/surendra/Downloads/wSterimol/wsterimol/weight.py
PyMOL>run /home/surendra/Downloads/wSterimol/wsterimol/wSterimol.py
PyMOL>run make_shell_figures.py,main
2020-11-26 17:28:38,462|DEBUG|Logging to stdout
2020-11-26 17:28:39,224|DEBUG|Read 1 conformers from CHEMBL2110918.sdf.bz2.
2020-11-26 17:28:39,382|DEBUG|Shell with identifier 661922864 at level 2 is not unique. Removing.
2020-11-26 17:28:39,382|DEBUG|Shell with identifier 1057074403 at level 2 is not unique. Removing.
2020-11-26 17:28:39,382|DEBUG|Shell with identifier 1266914156 at level 2 is not unique. Removing.
2020-11-26 17:28:39,383|DEBUG|Shell with identifier 1266914156 at level 2 is not unique. Removing.
2020-11-26 17:28:39,383|DEBUG|Shell with identifier 1936833248 at level 2 is not unique. Removing.
2020-11-26 17:28:39,406|DEBUG|Shell with identifier -2120100613 at level 3 is not unique. Removing.
2020-11-26 17:28:39,406|DEBUG|Shell with identifier -1459558800 at level 3 is not unique. Removing.
2020-11-26 17:28:39,406|DEBUG|Shell with identifier -889949098 at level 3 is not unique. Removing.
2020-11-26 17:28:39,406|DEBUG|Shell with identifier -260691027 at level 3 is not unique. Removing.
2020-11-26 17:28:39,407|DEBUG|Shell with identifier -115025741 at level 3 is not unique. Removing.
2020-11-26 17:28:39,407|DEBUG|Shell with identifier 35460490 at level 3 is not unique. Removing.
2020-11-26 17:28:39,407|DEBUG|Shell with identifier 300886491 at level 3 is not unique. Removing.
2020-11-26 17:28:39,407|DEBUG|Shell with identifier 383466322 at level 3 is not unique. Removing.
2020-11-26 17:28:39,407|DEBUG|Shell with identifier 525661536 at level 3 is not unique. Removing.
2020-11-26 17:28:39,408|DEBUG|Shell with identifier 586904987 at level 3 is not unique. Removing.
2020-11-26 17:28:39,408|DEBUG|Shell with identifier 671792618 at level 3 is not unique. Removing.
2020-11-26 17:28:39,408|DEBUG|Shell with identifier 1782835959 at level 3 is not unique. Removing.
2020-11-26 17:28:39,408|DEBUG|No new shells added. Convergence reached.
added edge between 236364480 and 4222155853
added edge between 236364480 and 4222155853
added edge between 3079013085 and 4222155853
added edge between 236364480 and 4222155853
added edge between 3654310210 and 4222155853
added edge between 3654310210 and 4222155853
added edge between 2523886517 and 3471456286
added edge between 3560653707 and 3471456286
added edge between 1355662222 and 2219502143
added edge between 3471456286 and 2219502143
added edge between 563733172 and 2219502143
added edge between 3654310210 and 2219502143
added edge between 486993694 and 2219502143
added edge between 3654310210 and 2219502143
added edge between 486993694 and 2219502143
added edge between 1377583001 and 2219502143
added edge between 3079013085 and 2219502143
added edge between 2453405156 and 236364480
added edge between 2453405156 and 236364480
added edge between 2453405156 and 236364480
added edge between 2453405156 and 3654310210
added edge between 2453405156 and 3654310210
added edge between 2738552880 and 3654310210
added edge between 2453405156 and 3654310210
added edge between 2453405156 and 3654310210
added edge between 2738552880 and 3654310210
added edge between 526356276 and 486993694
added edge between 526356276 and 486993694
added edge between 3560653707 and 486993694
added edge between 526356276 and 486993694
added edge between 526356276 and 486993694
added edge between 3560653707 and 486993694
added edge between 3560653707 and 1377583001
added edge between 526356276 and 1377583001
added edge between 2523886517 and 1377583001
added edge between 3560653707 and 1377583001
added edge between 3560653707 and 1355662222
added edge between 3560653707 and 1355662222
added edge between 2738552880 and 1355662222
added edge between 526356276 and 1355662222
added edge between 3471456286 and 3588767207
added edge between 486993694 and 3588767207
added edge between 1355662222 and 3588767207
added edge between 3079013085 and 3588767207
added edge between 1377583001 and 3588767207
added edge between 3654310210 and 2146727905
added edge between 1355662222 and 2146727905
added edge between 236364480 and 2146727905
added edge between 3079013085 and 2146727905
added edge between 236364480 and 2146727905
added edge between 3654310210 and 2146727905
added edge between 236364480 and 2146727905
added edge between 486993694 and 285017645
added edge between 1355662222 and 285017645
added edge between 3471456286 and 285017645
added edge between 563733172 and 285017645
added edge between 486993694 and 285017645
added edge between 1377583001 and 285017645
added edge between 2453405156 and 236364480
added edge between 2453405156 and 236364480
added edge between 2453405156 and 236364480
added edge between 526356276 and 563733172
added edge between 526356276 and 563733172
added edge between 526356276 and 563733172
added edge between 486993694 and 714291194
added edge between 3654310210 and 714291194
added edge between 1355662222 and 714291194
added edge between 1377583001 and 714291194
added edge between 3079013085 and 714291194
added edge between 563733172 and 714291194
added edge between 486993694 and 714291194
added edge between 3079013085 and 3982335018
added edge between 3471456286 and 3982335018
added edge between 236364480 and 3982335018
added edge between 236364480 and 3982335018
added edge between 3654310210 and 3982335018
added edge between 486993694 and 3982335018
added edge between 3654310210 and 3982335018
added edge between 1377583001 and 3982335018
added edge between 1355662222 and 3982335018
added edge between 236364480 and 3982335018
added edge between 2738552880 and 3079013085
added edge between 2453405156 and 3079013085
added edge between 2453405156 and 3079013085
added edge between 3560653707 and 3079013085
added edge between 2453405156 and 236364480
added edge between 2453405156 and 236364480
added edge between 2453405156 and 236364480
Traceback (most recent call last):
  File "/home/surendra/anaconda3/envs/e3fp/lib/python3.6/site-packages/networkx/classes/function.py", line 678, in set_node_attributes
    for n, v in values.items():
AttributeError: 'str' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/surendra/anaconda3/envs/e3fp/lib/python3.6/site-packages/pymol/parsing.py", line 487, in run
    run_(path, ns_main, ns_main)
  File "/home/surendra/anaconda3/envs/e3fp/lib/python3.6/site-packages/pymol/parsing.py", line 532, in run_file
    execfile(file,global_ns,local_ns)
  File "/home/surendra/anaconda3/envs/e3fp/lib/python3.6/site-packages/pymol/parsing.py", line 527, in execfile
    exec(co, global_ns, local_ns)
  File "make_shell_figures.py", line 600, in <module>
    only_unique=True)
  File "make_shell_figures.py", line 163, in create_shell_graph
    nx.set_node_attributes(G, 'shell', identifier_to_shell)
  File "/home/surendra/anaconda3/envs/e3fp/lib/python3.6/site-packages/networkx/classes/function.py", line 685, in set_node_attributes
    G.nodes[n][name] = values
TypeError: unhashable type: 'dict'


Waiting for positive help.

Thanks.

**Comment by sethaxen** [comment] 2021-01-05 04:28
Hi @VirtualChemist, I'm sorry for the delay. Would this still be useful for you? If so, I'll look into it ASAP.

**Comment by VirtualChemist** [comment] 2021-01-05 05:18
Yes, Please, we actually need it.

**Comment by sethaxen** [comment] 2021-01-05 09:14
@VirtualChemist I spent a few hours this evening trying to get an environment set up with a working PyMOL and e3fp, with no success. It's been a while since I last used the two together. Looks like you were successful. Could you by any chance share how you set that up?

**Comment by VirtualChemist** [comment] 2021-01-05 09:48
here is the set of command, which I used to setup e3fp and pymol. 
just make sure, you must have a valid licence for pymol. it is free and can be obtained from pymol website. You can find here in the attachment.

conda install -c keiserlab e3fp
conda install -c conda-forge pygraphviz
conda install -c conda-forge networkx
conda install -c conda-forge matplotlib
conda install -c conda-forge seaborn
conda install -c schrodinger pymol


[pymol-edu-license.zip](https://github.com/keiserlab/e3fp/files/5769345/pymol-edu-license.zip)

just extract and place anywhere in your system and browse to the path, when pymol ask.

**Comment by sethaxen** [comment] 2021-01-09 01:58
Thanks! I found out someone created an e3fp recipe on conda-forge that grabs the latest version from here, so this worked:
```bash
conda create -c conda-forge -c schrodinger --name e3fp_env python=3 e3fp standardiser scikit-learn pygraphviz networkx matplotlib seaborn pymol
```
I was able to reproduce the error you saw and will work on a fix.

**Comment by VirtualChemist** [comment] 2021-01-15 01:02
Hi Dr Seth,

Thanks for your kind help.
**Yes, I was able to run the first command:**
(ml-project) [surendra@gpu visualization]$ pymol -r make_shell_figures.py -- CHEMBL2110918.sdf.bz2

But, when I ran the **second command** to draw the graph. **I encountered some error. Is this normal.**

(ml-project) [surendra@gpu visualization]$ python draw_graph.py CHEMBL2110918
Rank: 0
 526356276	820
 2453405156	484
 2523886517	949
 2738552880	48
 3560653707	907
Rank: 1
 236364480	704
 486993694	798
 563733172	692
 1355662222	910
 1377583001	921
 3079013085	733
 3471456286	30
 3654310210	322
Rank: 2
 285017645	557
 714291194	1018
 2146727905	993
 2219502143	575
 3588767207	487
 3982335018	42
 4222155853	77
/home/surendra/anaconda3/envs/ml-project/lib/python3.8/site-packages/pygraphviz/agraph.py:1390: RuntimeWarning: Warning: node 'mol_plain', graph '' size too small for label
Warning: node 'mol_atom_types', graph '' size too small for label
Warning: node '1377583001', graph '' size too small for label
Warning: node '236364480', graph '' size too small for label
Warning: node '3079013085', graph '' size too small for label
Warning: node '3654310210', graph '' size too small for label
Warning: node '1355662222', graph '' size too small for label
Warning: node '3471456286', graph '' size too small for label
Warning: node '486993694', graph '' size too small for label
Warning: node '563733172', graph '' size too small for label
Warning: node '2146727905', graph '' size too small for label
Warning: node '3588767207', graph '' size too small for label
Warning: node '2219502143', graph '' size too small for label
Warning: node '3982335018', graph '' size too small for label
Warning: node '714291194', graph '' size too small for label
Warning: node '285017645', graph '' size too small for label
Warning: node '4222155853', graph '' size too small for label

  warnings.warn(b"".join(errors).decode(self.encoding), RuntimeWarning)
30
 42
 48
 77
 322
 484
 487
 557
 575
 692
 704
 733
 798
 820
 907
 910
 921
 949
 993
 1018
**Exception ignored in: <function AGraph.__del__ at 0x2ad4d7eaf820>
Traceback (most recent call last):
  File "/home/surendra/anaconda3/envs/ml-project/lib/python3.8/site-packages/pygraphviz/agraph.py", line 285, in __del__
  File "/home/surendra/anaconda3/envs/ml-project/lib/python3.8/site-packages/pygraphviz/agraph.py", line 1000, in _close_handle
TypeError: 'NoneType' object is not callable**
(ml-project) [surendra@gpu visualization]$ 

With regards,

**Comment by sethaxen** [comment] 2021-01-15 01:13
No, that's not an error I'm seeing. Can you try again in a clean conda environment and share the environment using `conda list --export`?

**Comment by VirtualChemist** [comment] 2021-01-15 01:14
okay, I will share soon.

**Comment by VirtualChemist** [comment] 2021-01-15 02:06
Hi Dr Seth,

Thanks, it worked perfectly.

I created a clean conda environment and created the graph.

here is the coda list.

conda list --export
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=conda_forge
_openmp_mutex=4.5=1_gnu
apbs=1.5=hd8ae8d1_0
boost=1.74.0=py38hf6732f7_2
boost-cpp=1.74.0=h9d3c048_1
brotlipy=0.7.0=py38h497a2fe_1001
bzip2=1.0.8=h7f98852_4
c-ares=1.17.1=h36c2ea0_0
ca-certificates=2020.12.5=ha878542_0
cached-property=1.5.1=py_0
cairo=1.16.0=h7979940_1007
certifi=2020.12.5=py38h578d9bd_1
cffi=1.14.4=py38ha65f79e_1
chardet=4.0.0=py38h578d9bd_1
cryptography=3.3.1=py38h2b97feb_1
curl=7.71.1=he644dc0_8
cycler=0.10.0=py_2
dbus=1.13.6=hfdff14a_1
decorator=4.4.2=py_0
e3fp=1.2.2=py38h709712a_0
expat=2.2.9=he1b5a44_2
fontconfig=2.13.1=hba837de_1004
freemol=1.158=py_2
freetype=2.10.4=h0708190_1
fribidi=1.0.10=h36c2ea0_0
gettext=0.19.8.1=h0b5b191_1005
glew=2.1.0=h9c3ff4c_2
glib=2.66.4=hcd2ae1e_1
graphite2=1.3.13=h58526e2_1001
graphviz=2.42.3=h0511662_0
gst-plugins-base=1.14.5=h0935bb2_2
gstreamer=1.18.3=h3560a44_0
h5py=3.1.0=nompi_py38hafa665b_100
harfbuzz=2.7.4=h5cf4720_0
hdf4=4.2.13=h10796ff_1004
hdf5=1.10.6=nompi_h7c3c948_1111
icu=68.1=h58526e2_0
idna=2.10=pyh9f0ad1d_0
joblib=1.0.0=pyhd8ed1ab_0
jpeg=9d=h36c2ea0_0
kiwisolver=1.3.1=py38h1fd1430_1
krb5=1.17.2=h926e7f8_0
lcms2=2.11=hcbb858e_1
ld_impl_linux-64=2.35.1=hea4e1c9_1
libblas=3.9.0=7_openblas
libcblas=3.9.0=7_openblas
libclang=11.0.0=default_ha5c780c_2
libcurl=7.71.1=hcdd3856_8
libedit=3.1.20191231=he28a2e2_2
libev=4.33=h516909a_1
libevent=2.1.10=hcdb4288_3
libffi=3.3=h58526e2_2
libgcc-ng=9.3.0=h5dbcf3e_17
libgfortran-ng=7.5.0=hae1eefd_17
libgfortran4=7.5.0=hae1eefd_17
libglib=2.66.4=h164308a_1
libglu=9.0.0=he1b5a44_1001
libgomp=9.3.0=h5dbcf3e_17
libholoplaycore=0.1.0_rc4=1
libiconv=1.16=h516909a_0
liblapack=3.9.0=7_openblas
libllvm11=11.0.1=hf817b99_0
libnetcdf=4.7.4=nompi_h56d31a8_107
libnghttp2=1.41.0=h8cfc5f6_2
libopenblas=0.3.12=pthreads_hb3c22a3_1
libpng=1.6.37=h21135ba_2
libpq=12.3=h255efa7_3
libssh2=1.9.0=hab1572f_5
libstdcxx-ng=9.3.0=h2ae2ef3_17
libtiff=4.2.0=hdc55705_0
libtool=2.4.6=h58526e2_1007
libuuid=2.32.1=h7f98852_1000
libwebp-base=1.1.0=h36c2ea0_3
libxcb=1.13=h7f98852_1003
libxkbcommon=1.0.3=he3ba5ed_0
libxml2=2.9.10=h72842e0_3
lz4-c=1.9.3=h9c3ff4c_0
matplotlib=3.3.3=py38h578d9bd_0
matplotlib-base=3.3.3=py38h0efea84_0
mengine=1=h14c3975_1
mmcif_pdbx=1.1.2=pyh9f0ad1d_0
mmh3=2.5.1=py38h709712a_3
mpeg_encode=1=h14c3975_1
mtz2ccp4_px=1.0=h9ac9557_3
mysql-common=8.0.22=ha770c72_1
mysql-libs=8.0.22=h1fd7589_1
ncurses=6.2=h58526e2_4
networkx=2.5=py_0
nspr=4.29=h9c3ff4c_1
nss=3.60=hb5efdd6_0
numpy=1.19.5=py38h18fd61f_1
olefile=0.46=pyh9f0ad1d_1
openssl=1.1.1i=h7f98852_0
pandas=1.2.0=py38h51da96c_1
pango=1.42.4=h69149e4_5
patsy=0.5.1=py_0
pcre=8.44=he1b5a44_0
pdb2pqr=3.1.0=pyhd3deb0d_1
pillow=8.1.0=py38h357d4e7_1
pip=20.3.3=pyhd8ed1ab_0
pixman=0.40.0=h36c2ea0_0
pmw=2.0.1=py38h578d9bd_1004
propka=3.4.0=py38h81c977d_1
pthread-stubs=0.4=h36c2ea0_1001
pycairo=1.20.0=py38h323dad1_1
pycparser=2.20=pyh9f0ad1d_2
pygraphviz=1.6=py38h25c7686_1
pymol=2.4.1=py38h4463551_0
pyopenssl=20.0.1=pyhd8ed1ab_0
pyparsing=2.4.7=pyh9f0ad1d_0
pyqt=5.12.3=py38h578d9bd_7
pyqt-impl=5.12.3=py38h7400c14_7
pyqt5-sip=4.19.18=py38h709712a_7
pyqtchart=5.12=py38h7400c14_7
pyqtwebengine=5.12.1=py38h7400c14_7
pysocks=1.7.1=py38h578d9bd_3
python=3.8.6=hffdb5ce_4_cpython
python-dateutil=2.8.1=py_0
python_abi=3.8=1_cp38
pytz=2020.5=pyhd8ed1ab_0
qt=5.12.9=h9d6b050_2
rdkit=2020.09.3=py38h2bca085_0
readline=8.0=he28a2e2_2
reportlab=3.5.59=py38hadf75a6_0
requests=2.25.1=pyhd3deb0d_0
rigimol=1.3=2
scikit-learn=0.24.0=py38h658cfdd_0
scipy=1.5.3=py38h828c644_0
sdaxen_python_utilities=0.1.4=pyhd3deb0d_0
seaborn=0.11.1=ha770c72_0
seaborn-base=0.11.1=pyhd8ed1ab_0
setuptools=49.6.0=py38h578d9bd_3
six=1.15.0=pyh9f0ad1d_0
sqlalchemy=1.3.22=py38h497a2fe_1
sqlite=3.34.0=h74cdb3f_0
standardiser=0.1.9=pyh9f0ad1d_0
statsmodels=0.12.1=py38h5c078b8_2
threadpoolctl=2.1.0=pyh5ca1d4c_0
tk=8.6.10=h21135ba_1
tornado=6.1=py38h497a2fe_1
urllib3=1.26.2=pyhd8ed1ab_0
wheel=0.36.2=pyhd3deb0d_0
xorg-kbproto=1.0.7=h7f98852_1002
xorg-libice=1.0.10=h516909a_0
xorg-libsm=1.2.3=h84519dc_1000
xorg-libx11=1.6.12=h516909a_0
xorg-libxau=1.0.9=h7f98852_0
xorg-libxdmcp=1.1.3=h7f98852_0
xorg-libxext=1.3.4=h516909a_0
xorg-libxpm=3.5.13=h516909a_0
xorg-libxrender=0.9.10=h516909a_1002
xorg-libxt=1.1.5=h516909a_1003
xorg-renderproto=0.11.1=h14c3975_1002
xorg-xextproto=7.3.0=h7f98852_1002
xorg-xproto=7.0.31=h7f98852_1007
xz=5.2.5=h516909a_1
zlib=1.2.11=h516909a_1010
zstd=1.4.8=ha95c52a_1

Once again thank you so much for your kind cooperation and help.

With regards,

**Comment by sethaxen** [comment] 2021-01-15 05:17
Great! Glad to hear it. As a final word of caution, while with open source software there are no guarantees that things work correctly, this is especially the case with the e3fp-paper repo, which is neither tested nor regularly maintained. Use at your own risk. 🙂 

Closing this issue as it appears the original issue has been resolved.

**Closed by sethaxen** 2021-01-15 05:17 UTC
